### PR TITLE
gm命令初始化移入Service层

### PR DESCRIPTION
**Pull request by cbwsnr**

### CODE REVIEW

**Comment by pwnhub1024** [comment]
CommandInfoService.java 里面的重复set代码是不是改成这样会简洁一些
CommandInfoDO.class加一个构造函数
public class CommandInfoDO {
    private String syntax;
    private int level;
    private String commandClassName;

    public CommandInfoDO(String syntax, int level, String commandClassName) {
        this.syntax = syntax;
        this.level = level;
        this.commandClassName = commandClassName;
    }

    // 其他 getter 和 setter 方法
}
方法体调用
public List<CommandInfoDO> getLv0Commands() {
    return List.of(new CommandInfoDO("help", 0, "HelpCommand"));
}

**Comment by pwnhub1024** [comment]
``` java
public List<CommandInfoDO> getLv0Commands() {
    List<CommandInfoDO> results = new ArrayList<>();

    // 使用辅助方法添加命令
    addCommand(results, "help", 0, "HelpCommand");
    addCommand(results, "commands", 0, "HelpCommand");
    addCommand(results, "droplimit", 0, "DropLimitCommand");

    return results;
}

private void addCommand(List<CommandInfoDO> results, String syntax, int level, String commandClassName) {
    CommandInfoDO commandInfoDO = new CommandInfoDO();
    commandInfoDO.setSyntax(syntax);
    commandInfoDO.setLevel(level);
    commandInfoDO.setCommandClassName(commandClassName);
    results.add(commandInfoDO);
}
```
或者这样子，后续如果要扩展也不用复制重复的new CommandInfoDO()

**Comment by cbwsnr** [comment]
好的。defaultLevel这个字段要放到构造函数中。后续从数据库读取的话，这些重复代码都会删掉

**Comment by nu1lkali** [comment]
List<String> packageNames = List.of(
    "org.gms.client.command.commands.gm0",
    "org.gms.client.command.commands.gm1",
    "org.gms.client.command.commands.gm2",
    "org.gms.client.command.commands.gm3",
    "org.gms.client.command.commands.gm4",
    "org.gms.client.command.commands.gm5",
    "org.gms.client.command.commands.gm6"
);

for (String packageName : packageNames) {
    commandClassList.addAll(getPackageClasses(packageName));
}
导包的方法可以这样改

**Comment by pwnhub1024** [comment]
IntStream.rangeClosed(0, 6)
         .mapToObj(i -> "org.gms.client.command.commands.gm" + i)
         .forEach(packageName -> commandClassList.addAll(getPackageClasses(packageName)));
反正gm包是0-6有序的 不如这样子

**Pull request merged**
